#135 : separate the header naming convention from parameterNamingConvention
OpenAPITools/openapi-style-validator pull request #141
Opened 2021-01-12 21:37 UTC by mohamedelhabib

2021-01-13 14:07 UTC, JFCote requested changes
Only a small missing space and everything else looks good to me.

2021-01-13 14:07 UTC, JFCote commented on lib/src/main/java/org/openapitools/openapistylevalidator/NamingValidator.java
> +            if(isUpperCase) {
please do a "reformat" here or juste add a space between `if` and `(`.

2021-01-13 14:40 UTC, JFCote approved these changes
LGTM. Will merge shortly

2021-01-13 15:44 UTC, merged

2021-01-13 17:36 UTC, mohamedelhabib commented
@JFCote Thanks for the quick merge. 
Did you know when this will be released ?

2021-01-13 17:56 UTC, JFCote commented
@jmini is the only one currently able to do a release. I have no problem doing one after this PR has passed CI: https://github.com/OpenAPITools/openapi-style-validator/pull/104

So @jmini let me know over slack when you think you'll be able to do a release.

2021-01-18 06:13 UTC, jmini commented
@mohamedelhabib:

I have released version `1.5` of `openapi-style-validator`
https://github.com/OpenAPITools/openapi-style-validator/releases/tag/1.5