Fix 178, should not fail when there are no 'example' for a component
OpenAPITools/openapi-style-validator pull request #179
Opened 2021-03-30 12:44 UTC by gervaisb

This fix the issue #178 by excluding poperties with a defined `allOf` from the example validation.

2021-04-05 12:31 UTC, JFCote commented
@gervaisb Thanks for your contribution. I need some time to check this and right now I'm in the middle of a big project. Will check this in 2 weeks.

2021-05-10 12:35 UTC, JFCote commented
@gervaisb  I did not forget about you. Just been very busy ! I'm also having problem with the sonarqube validation that is done on each commit. Checking this with the people of openapitools who manage the organization. Will try to get back to you as soon as possible. Sorry about the delay!

2021-06-15 16:43 UTC, JFCote requested changes

2021-06-15 16:43 UTC, JFCote commented on lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java
> +                            property.getAllOf()==null) {
Please do a little reformat here with space before and after the `==`.
Like this:
```suggestion
                            property.getAllOf() == null) {
```

2021-06-15 16:44 UTC, JFCote approved these changes

2021-06-28 16:35 UTC, merged

2021-06-29 05:44 UTC, gervaisb commented
Hey, thank you for your review and merge.

Any idea when this will be released ?

On Mon, 28 Jun 2021 at 18:35, Jean-François Côté ***@***.***>
wrote:

> Merged #179
> <https://github.com/OpenAPITools/openapi-style-validator/pull/179> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenAPITools/openapi-style-validator/pull/179#event-4948556131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAKSLYWYQESIB3RVUWA7TUDTVCQENANCNFSM42B6WXYA>
> .
>

2021-06-29 11:28 UTC, JFCote commented
@gervaisb I will check with @jmini . He's the one with the key ready for the release.

2021-06-29 12:26 UTC, JFCote commented
@gervaisb Should be done within the end of the week for version 1.7

2021-06-30 12:24 UTC, JFCote commented
@gervaisb It's been released!!