[WIP] write existing rules as per new design.
OpenAPITools/openapi-style-validator pull request #464
Opened 2022-12-23 14:53 UTC by thiyagu06

Follow up of #400 .

2022-12-23 16:14 UTC, JFCote requested changes
Very nice first draft! Here are a couple of small tweak I suggest. I can also see there seems to be a problem with the automatic build.

2022-12-23 16:14 UTC, JFCote commented on lib/build.gradle
> +    implementation group: 'org.apache.commons', name: 'commons-lang3', version: '3.12.0'
Please keep the implementation near the other implementation. I like to keep `implementation` and `testImplementation` in separated blocks :)

2022-12-23 16:14 UTC, JFCote commented on lib/src/test/java/org/openapitools/openapistylevalidator/rules/ContactInfoRuleTest.java
> +    private OpenAPI createOpenApi() {
I would rename this `createValidOpenApi`

2022-12-23 16:14 UTC, JFCote commented on lib/src/test/java/org/openapitools/openapistylevalidator/rules/InfoDescriptionRuleTest.java
> +    private OpenAPI createOpenApi() {
I would rename this `createValidOpenApi`

2022-12-23 16:14 UTC, JFCote commented on lib/src/test/java/org/openapitools/openapistylevalidator/rules/LicenseRuleTest.java
> +    private OpenAPI createOpenApi() {
I would rename this `createValidOpenApi`

2022-12-23 16:14 UTC, JFCote commented on lib/src/test/java/org/openapitools/openapistylevalidator/rules/OpenAPIRuleTest.java
> +    private OpenAPI createOpenApi() {
I would rename this `createValidOpenApi`

2022-12-24 10:13 UTC, thiyagu06 commented
@JFCote I moved few existing rules https://github.com/OpenAPITools/openapi-style-validator/blob/master/lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java#L32-L34 into the new design. I feel we can take another one or two PR to move the remaining PR's. any thoughts?

2023-01-13 13:05 UTC, JFCote commented
> @JFCote I moved few existing rules https://github.com/OpenAPITools/openapi-style-validator/blob/master/lib/src/main/java/org/openapitools/openapistylevalidator/OpenApiSpecStyleValidator.java#L32-L34 into the new design. I feel we can take another one or two PR to move the remaining rules. any thoughts?

Hey @thiyagu06 , just came back from vacation. Will take a look at what you have done in the coming week! But yeah I think we can move a couple other rules but don't create a PR that is too big please :)

2023-01-27 12:19 UTC, JFCote approved these changes
LGTM. I suggest we merge this right now and you create a new PR for other rules

2023-01-27 12:20 UTC, merged

2023-01-27 12:20 UTC, JFCote commented
@thiyagu06 Merged! Please create another branch and PR for the other rules :)